### ISSUE TITLE
Flycheck fails to install

### ISSUE THREAD

**Issue by jamiees2** [xiaohanyu/oh-my-emacs#142]
Installing flycheck seems to fail on OSX Yosemite.
Emacs is installed under Homebrew.

Emacs version: `24.4.1`
Makeinfo version: `4.8`

Error: 
```
flycheck.texi:6: warning: unrecognized encoding name `UTF-8'.
flycheck.texi:86: @pxref expected braces.
flycheck.texi:86: ` {Installation}
and @ref{Quickstart} res...' is too long for expansion; not expanded.
flycheck.texi:86: First argument to cross-reference may not be empty.
/Users/james/.emacs.d/el-get/flycheck/doc//flycheck.texi:75: Next reference to nonexistent node `Introduction' (perhaps incorrect sectioning?).
/Users/james/.emacs.d/el-get/flycheck/doc//flycheck.texi:85: Cross reference to nonexistent node `Introduction' (perhaps incorrect sectioning?).
makeinfo: Removing output file `/Users/james/.emacs.d/el-get/flycheck/doc/flycheck.info' due to errors; use --force to preserve.
```

The error seemed to be related to #47, but this is the latest version of el-get.

**Comment by xiaohanyu** [comment]
How about ` brew link texinfo --force` and try again?

**Comment by jamiees2** [comment]
Great! That works!

Thanks for all your hard work.

**Comment by xiaohanyu** [comment]
You are welcome. Check https://github.com/xiaohanyu/oh-my-emacs/blob/c664894e2f1c1cb0f95a9f2da88d41b00f190856/core/ome-basic.org#homebrew and https://github.com/xiaohanyu/oh-my-emacs/issues/85 for technical details, if you're interested.

**Comment by marksix** [comment]
I did as you said but still failed. 
The error info is the same with jamiees2

**Comment by xuchunyang** [comment]
> I did as you said but still failed. 
> The error info is the same with jamiees2

What's the output of `which texinfo` and `texinfo --version`?

**Comment by marksix** [comment]
I'm running on OS X 10.10
I have installed `texinfo` from homebrew and link them to my path.
However I don't have `texinfo` in my path, but I have `info`, `makeinfo`, etc.
`info --version` return `5.2`.

**Comment by jamiees2** [comment]
Same here by the way :smile:

**Comment by marksix** [comment]
Hi jamiees, 
your installation is successful now?

**Comment by jamiees2** [comment]
Yes, it is. Been running fine for 5 days.

**Comment by jamiees2** [comment]
@marksix did you take a look at #47 that I linked aswell? Might be something there aswell.

**Comment by jamiees2** [comment]
Also, what Emacs version are you using? The default OSX one isn't compatible. What is the output of `emacs -version` ?

**Comment by marksix** [comment]
I installed emacs from homebrew and built with imagmagick, gnutls.
`emacs -version` returned 25.0.50.1

**Comment by jamiees2** [comment]
Hmm, then I don't know :tongue:

**Comment by marksix** [comment]
I run emacs in gui application and installation failed.
Now I run it within terminal and it succeeded.
I don't understand how it happens but it's working now.
Thank for your kindly help, friends.

**Comment by xiaohanyu** [comment]
This is really weird, I also run Emacs on Mac OS X 10.10 and I met no problems. I'll keep an eye on this problem.

**Comment by jamiees2** [comment]
Could it be that you forgot to run `brew linkapps`? The GUI version might still running the default OSX version, while `emacs` is the brew version.

**Comment by xiaohanyu** [comment]
Things on Mac OS X is a little complicated due to:

1. Mac has different package managers, macports/homebrew
2. Even homebrew has two ways to install emacs, one way is to install emacs by `brew install emacs`, and another way is to install emacs by `brew cask install emacs`
3. The GUI apps on Mac OS X has different `$PATH` with terminal(bash/zsh)

So it's not easy to track all these kind of problems in a simple way. The best way I can figure out is to provide binary distribution of oh-my-emacs, however, I still didn't get enough time to implement this.

**Comment by jamiees2** [comment]
I think that might be a little drastic. I would simply post a setup FAQ in the wiki on how to get emacs + oh-my-emacs running properly with OSX and homebrew.

**Comment by jamiees2** [comment]
I didn't know about the `brew cask` setup, but it might be better, as I had some issues with the Homebrew setup. I'll probably reinstall Emacs later using cask instead.

**Comment by xiaohanyu** [comment]
I do have written a section about Mac OS X installation: https://github.com/xiaohanyu/oh-my-emacs/blob/master/core/ome-basic.org#mac-os-x-compatibilities .

However, trying to build an `.emacs.d` from source(instead of binary, I mean, download and extract) may have some unexpected problems during installation. For instance, one man install oh-my-emacs successfully today but it may failed to install oh-my-emacs again. Oh-my-emacs depends on el-get, and el-get will download lots of things from internet, different packages have different dependencies, different package versions and may have incompatibility problems between Emacs 24.3 and 24.4 and 25.0.

So I think a better way to workaround this problem is https://github.com/xiaohanyu/oh-my-emacs/issues/99 . But I didn't got enough time to implement this for now, forgive me.

**Comment by erson** [comment]
makeinfo 5.2 is working version for overwhelming the flycheck issue.(for osx Ver. 10.9.5-mavericks)

To get it work:

update your texinfo package with brew update && brew install texinfo 
after installation complete you need to check which version of makeinfo is used.At my situataion it was still 4.8 version.(which makeinfo && makeinfo --version)

for standart homebrew installation all packeges are put under /usr/local/Cellar after brew install ...

so before moving the orginal makeinfo file go to /usr/local/Cellar and check if there is texinfo/5.2 folder or not.if it isnt there it is probably at the homebrew's user defined custom package folder.


sudo mv /usr/bin/makeinfo /usr/bin/mknfo.bkp 
sudo ln -s /usr/local/Cellar/texinfo/5.2/bin/make /usr/bin/makeinfo

after this, run emacs and wait it finishes it job.(oh-my-emacs installation stuck at flycheck.)

meanwhile if you get any kind of "let-alist" error, install it from elpa repos: https://elpa.gnu.org/packages/let-alist.html (M-x install-package RET let-alist RET) this would solve the problem.
